# Programming assignment 1

In [1]:
import numpy as np
import requests
from io import BytesIO
from zipfile import ZipFile
from scipy.io import loadmat
import os
from matplotlib import pyplot as plt
%matplotlib notebook

In [2]:
if not os.path.exists("./quiz6/"):
    zipquiz = ("http://spark-public.s3.amazonaws.com"
               "/neuralnets/Programming%20Assignments"
               "/Programming%20Assignment%201/Assignment1.zip")
    quiz_req = requests.get(zipquiz)
    zipped = ZipFile(BytesIO(quiz_req.content))
    zipped.extractall(path="./quiz6/")

** Datasets **
 1. `neg_example_nobias`: Matrix containing examples belonging to class 0
 2. `pos_example_nobias`: Matrix containing examples belloinging to class 1
 3. `w_init`: Some initial weight vector
 4. `w_gen_feas`: A generously feasible weight vector

In [3]:
dataset1 = loadmat("./quiz6/Datasets/dataset1.mat")
dataset1

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, written by Octave 3.2.4, 2012-10-03 23:31:57 UTC',
 '__version__': '1.0',
 'neg_examples_nobias': array([[-0.80857143,  0.8372093 ],
        [ 0.35714286,  0.85049834],
        [-0.75142857, -0.73089701],
        [-0.3       ,  0.12624585]]),
 'pos_examples_nobias': array([[ 0.87142857,  0.62458472],
        [-0.02      , -0.92358804],
        [ 0.36285714, -0.31893688],
        [ 0.88857143, -0.87043189]]),
 'w_gen_feas': array([[ 4.3496526 ],
        [-2.60997235],
        [-0.69414749]]),
 'w_init': array([[-0.62170147],
        [ 0.76091527],
        [ 0.77187205]])}

In [63]:
vect1 = np.ones(len(dataset1["neg_examples_nobias"]))

Xtest_neg = np.c_[dataset1["neg_examples_nobias"], vect1]
Xtest_pos = np.c_[dataset1["pos_examples_nobias"], vect1]

In [70]:
predict_neg = Xtest_neg @ dataset1["w_init"]
predict_pos = Xtest_pos @ dataset1["w_init"]

In [106]:
np.flatnonzero(predict_neg >= 0)

array([0, 1, 2, 3])

In [107]:
dataset1["w_init"].T - Xtest_neg[_,:]

array([[ 0.18686995, -0.07629403, -0.22812795],
       [-0.97884433, -0.08958307, -0.22812795],
       [ 0.1297271 ,  1.49181228, -0.22812795],
       [-0.32170147,  0.63466943, -0.22812795]])

In [103]:
np.flatnonzero(predict_pos < 0)

array([3])

In [104]:
dataset1["w_init"].T + Xtest_pos[_,:]

array([[ 0.26686995, -0.10951662,  1.77187205]])

# Testing the Perceptron Class

In [4]:
import sys
sys.path.append("..")
from perceptron import Perceptron

In [5]:
neg_examples = dataset1["neg_examples_nobias"]
pos_examples = dataset1["pos_examples_nobias"]

perc1 = Perceptron(neg_examples, pos_examples)